phantomjs:
  image: cmfatih/phantomjs
  entrypoint:
    - phantomjs
    - /app/phantomjs-runner.js
    - http://static/gvcharts.html
  ports:
    - "6666:80"
  volumes:
    - app:/app
    - .tmp/:/var/phantomjs/
  links:
    - static
  restart: always
  mem_limit: 4G

static:
  build: ./containers/static
  ports:
    - "8081:80"
  volumes:
    - ./tmp/static:/usr/share/nginx/html
  restart: always

proxy:
  build: ./containers/proxy
  ports:
    - "80:80"
  links:
    - phantomjs
  restart: always
