phantomjs:
  image: cmfatih/phantomjs
  entrypoint:
    - phantomjs
    - /app/phantomjs-runner.js
    - http://static/chart/
  ports:
    - "6666:80"
  volumes:
    - containers/phantomjs/app:/app
  links:
    - static
  restart: always
  mem_limit: 4G

static:
  build: ./containers/static
  ports:
    - "8080:80"
  restart: always

proxy:
  build: ./containers/proxy
  ports:
    - "80:80"
  links:
    - phantomjs
    - redis
  restart: always

redis:
  image: redis
